ALTER TABLE characters
    ADD COLUMN IF NOT EXISTS trust INT NOT NULL DEFAULT 50,
    ADD COLUMN IF NOT EXISTS intimacy INT NOT NULL DEFAULT 50,
    ADD COLUMN IF NOT EXISTS respect INT NOT NULL DEFAULT 50;
